version: '3'
services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: macbook
            POSTGRES_DB: hello_books
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - '5432:5432'
    web:
        image: hello_books
        command: npm start
        volumes:
            - .:/app/
            - /app/node_modules
        restart: always
        build: .
        depends_on:
            - db
        ports:
            - '9001:4001'
